### ISSUE TITLE
How to refund invoice when amount has cents ?

### ISSUE THREAD

**Issue by zhuravskiy** [recurly/recurly-client-java#73]
**Describe the bug**

Do not see the way, how to refund  amount with cents. for example $12.50

https://developers.recurly.com/api/v2019-10-10/index.html#operation/refund_invoice

 `amount` property has `integer`, looks like wrong. should be  `float` type.

 2nd bug:
When i did refund $10, the refunded invoice has total refund amount $9.99. Where is 1 cent?

**To Reproduce**

Subscribe, then do invoice refund.

**Expected behavior**

**Your Environment**

sandbox

**Comment by douglasmiller** [comment]
> amount property has integer, looks like wrong. should be float type.

I think that you are correct. The `amount` property can be populated with a decimal value to reflect dollars and cents. I was able to reproduce this using one of our client libraries that is not statically typed.

I'll see about getting this updated quickly for you.

> When i did refund $10, the refunded invoice has total refund amount $9.99. Where is 1 cent?

I was not able to reproduce this particular issue. I'll continue to investigate this particular issue and will update this issue shortly

**Comment by douglasmiller** [comment]
@zhuravskiy As previously stated, I wasn't able to directly reproduce the second issue that you reported, but I have found the instance of the request in your sandbox account. 

We will perform a more in-depth investigation into this.

**Comment by zhuravskiy** [comment]
@douglasmiller thank you! I can provide requests /responses payloads or x-request-ids, any other info, just ping me.

**Comment by zhuravskiy** [comment]
After my little investigation: bug exists only for refund amounts $10 or less. 
For example, when I did refund amount $11 or $12, the total refund amount of the invoice has expected value (the same as requested - $11 and $12).

**Comment by douglasmiller** [comment]
@zhuravskiy, it turns out that this is actually expected behavior when applying open amount refunds. The reasoning behind it is fairly complex and I've spend the better part of today discussing the topic with other developers here to determine exactly what is happening.

The short version is that a new `refund_amount` and `tax` (per line item) are calculated to match the `original_total` that was included in the refund request. Rounding errors can occur that cause the refund amount to be +/-  1 cent (when dealing with USD).

I can provide more detail about what is happening and what scenarios can cause this +/- 1 rounding error to occur on Monday, if you'd like.

**Comment by douglasmiller** [comment]
@zhuravskiy Thank you again for reporting the issues with the `amount` field. We have made the appropriate updates to the API specification and an updated client will be published soon.

Do you need any additional clarification on the invoice refund process?

**Comment by zhuravskiy** [comment]
@douglasmiller thank you!
